loadBitmaps = function () {
    game.load.image('EndTurn', 'res/end_turn.png');
    game.load.image('Grass', 'res/grass.png');
    game.load.image('GrassMove', 'res/grass_move.png');
    game.load.image('GrassDamage', 'res/grass_damage.png');
    game.load.image('GrassAttack', 'res/grass_attack.png');
    game.load.image('GrassBoost', 'res/grass_boost.png');
    game.load.image('GrassFriendly', 'res/grass_friendly.png');
    game.load.image('GrassSelected', 'res/grass_selected.png');
    game.load.image('Border', 'res/border.png');
    game.load.image('shifter', 'res/shifter.png');

    game.load.image('Tree', 'res/tree.png');
    game.load.image('Wall', 'res/wall.png');
    // game.load.image('Fir', 'res/fir.png');
    game.load.image('Fir', 'res/withered_pine.png');
    game.load.image('Saurian', 'res/saurian.png');
    game.load.image('Stone', 'res/stone.png');
    game.load.image('Shooter', 'res/shooter.png');
    game.load.image('Native', 'res/native.png');
    game.load.image('Saberhand', 'res/saberhand.png');
    game.load.image('Destroyer', 'res/destroyer.png');
    game.load.image('Warrior', 'res/warrior.png');
    game.load.image('Rocket Thrower', 'res/thrower.png');
    game.load.image('Spider', 'res/spider.png');
    game.load.image('Sorcerer', 'res/sorcerer.png');
    game.load.image('Guardian', 'res/guardian.png');
    game.load.image('Golem', 'res/golem.png');
    game.load.image('Droid', 'res/droid.png');
    game.load.image('Commander', 'res/commander.png');
    game.load.image('Monk', 'res/monk.png');
    game.load.image('Poisoner', 'res/poisoner.png');
    game.load.image('Samurai', 'res/samurai.png');
    game.load.image('Sniper', 'res/sniper.png');
    game.load.image('Wolf', 'res/wolf.png');
    game.load.image('Spectre', 'res/spectre.png');
    game.load.image('Pixie', 'res/pixie.png');

    game.load.image('Saurian Web', 'res/saurian_web.png');

    game.load.image('moveable', 'res/moveable.png');
    game.load.image('sabers', 'res/sabers.png');
    game.load.image('invisibility', 'res/invisibility.png');
    game.load.image('bullet', 'res/bullet.png');
    game.load.image('grenade', 'res/grenade.png');
    game.load.image('tongue_of_fire', 'res/tongue_of_fire.png');

    game.load.image('bullet', 'res/bullet.png');
    game.load.image('bum', 'res/bum.png');
    game.load.image('grenade', 'res/grenade.png');
    game.load.image('detonation', 'res/detonation.png');
    game.load.image('sabers_attack', 'res/sabers_attack.png');
    game.load.image('tongue_of_fire', 'res/tongue_of_fire.png');
    game.load.image('saberhand_transparency', 'res/saberhand_transparency.png');
    game.load.image('drain', 'res/drain.png');
    game.load.image('counterattack', 'res/counterattack.png');
    game.load.image('native_attack', 'res/native_attack.png');
    game.load.image('magic_bullet', 'res/magic_bullet.png');
    game.load.image('magic_splash', 'res/magic_splash.png');
    game.load.image('monk_use_1', 'res/monk_use_1.png');
    game.load.image('monk_use_2', 'res/monk_use_2.png');
    game.load.image('monk_use_3', 'res/monk_use_3.png');
    game.load.image('blow_the_ax', 'res/blow_the_ax.png');
    game.load.image('armor', 'res/armor.png');
    game.load.image('warrior_blow', 'res/warrior_blow.png');
    game.load.image('warrior_attack', 'res/warrior_attack.png');
    game.load.image('warrior_immortal', 'res/warrior_immortal.png');
    game.load.image('immortality', 'res/immortality.png');
    game.load.image('prison_connection', 'res/prison_connection.png');
    game.load.image('protection_field', 'res/protection_field.png');
    game.load.image('sorcerer_attack', 'res/sorcerer_attack.png');
    game.load.image('sword_blow', 'res/sword_blow.png');
    game.load.image('samurai_sword_blow', 'res/samurai_sword_blow.png');
    game.load.image('dodge', 'res/rat.png');
    game.load.image('samurai_dodge', 'res/samurai_small.png');
    game.load.image('poisoned_missile', 'res/poisoned_missile.png');
    game.load.image('poisoned_missile_explosion', 'res/poisoned_missile_explosion.png');
    game.load.image('spear', 'res/spear.png');
    game.load.image('guardian_attack', 'res/guardian_attack.png');
    game.load.image('shield', 'res/shield.png');
    game.load.image('power_bullet', 'res/power_bullet.png');
    game.load.image('laser', 'res/laser.png');
    game.load.image('teleport', 'res/teleport.png');
    game.load.image('sniper_bullet', 'res/sniper_bullet.png');
    game.load.image('sniper_bullet_explosion', 'res/sniper_bullet_explosion.png');
    game.load.image('hypnosis', 'res/hypnosis.png');
    game.load.image('stone_skin', 'res/stone_skin.png');
    game.load.image('arrow', 'res/arrow.png');
    game.load.image('arrow_anim', 'res/arrow_anim.png');
    game.load.image('aura_of_destruction', 'res/aura_of_destruction.png');
    game.load.image('destruction_1', 'res/destruction_1.png');
    game.load.image('destruction_2', 'res/destruction_2.png');
    game.load.image('destruction_3', 'res/destruction_3.png');
    game.load.image('jaw_spider', 'res/jaw_spider.png');
    game.load.image('spider_web', 'res/spider_web.png');
    game.load.image('surroundings', 'res/surroundings.png');
    game.load.image('rocket', 'res/rocket.png');
    game.load.image('flame_thrower', 'res/flame_thrower.png');
    game.load.image('claws', 'res/claws.png');
    game.load.image('cleaver', 'res/cleaver.png');
    game.load.image('spectre_cleaver', 'res/spectre_cleaver.png');
    game.load.image('havoc', 'res/havoc.png');
    game.load.image('immateriality', 'res/immateriality.png');
    game.load.image('dark_forest', 'res/dark_forest.png');
    game.load.image('poke', 'res/poke.png');
    game.load.image('destroyer_attack', 'res/destroyer_attack.png');

    // effects
    game.load.image('viewfinder', 'res/arrow.png');
    game.load.image('poisoning', 'res/poisoning.png');
    game.load.image('power_bullet_effect', 'res/power_bullet.png');
    game.load.image('spider_web_slow', 'res/spider_web.png');
    game.load.image('hypnotised', 'res/hypnosis.png');


    game.load.onLoadComplete.add(loadCompleted, this);

    game.load.start();
};
